server:
    port: 8080

spring:
    application:
        name: helmesback
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:./data/helmes
        username: adm
        password:
    liquibase:
        enabled: true
        change-log: classpath:/db/changelog/db.changelog-master.yaml
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: false
        properties:
            hibernate:
                use_sql_comments: true
                format_sql: true
    h2:
        console:
            enabled: true
            path: /console